-- ============================================================================
-- V1__core_baseline.sql
-- Fresh-database baseline for the CORE tables.
--
-- WHY THIS EXISTS
-- ---------------
-- The original app created its core schema (users, submissions, feedbacks, …)
-- with Hibernate `ddl-auto`, and the numbered migrations start at V2 — they
-- ALTER / add foreign keys to those core tables assuming they already exist
-- (e.g. V3 `ALTER TABLE users`, V6 `submission_versions`, V7 `feedbacks`,
-- V8/V2 `REFERENCES units(id)`, V16 `submission_similarities`, V18 `ai_insights`).
-- Flyway runs BEFORE Hibernate, so on a brand-new database (Supabase) those
-- migrations would fail on missing tables and the app would not boot.
--
-- This migration creates just enough of each core table — the primary key —
-- so the additive V2→V19 chain applies cleanly. Every remaining column is then
-- added by Hibernate `ddl-auto=update` (which runs after Flyway) to match the
-- JPA @Entity mappings exactly, and by the specific V2→V19 ALTERs. Tables that
-- no migration references (courses, curriculum, enrollments, lecturer_profiles,
-- collaborations, …) are intentionally omitted — Hibernate creates those.
--
-- Idempotent (IF NOT EXISTS) so it is a no-op on any database that already has
-- the schema (e.g. an existing Railway/Postgres instance being adopted).
-- ============================================================================

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS submission_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS teaching_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS student_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS ai_insights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS submission_similarities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
